version: '3.8'
services:
  db-postgres:
    image: postgres:16-alpine3.19
    container_name: sbp_postgres_database
    restart: always
    environment:
      POSTGRES_DB: sbp_postgres_database
      POSTGRES_USER: sbp
      POSTGRES_PASSWORD: sbp
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - ./dev/ignore/database/db-data/postgres:/var/lib/postgresql/data
      - ./dev/database/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./src/main/resources/db/migration:/seed-data
  db-mysql:
    container_name: sbp_mysql_database
    image: "mysql:8.2-oracle"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./dev/database/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./dev/ignore/database/db-data/mysql:/var/lib/mysql
      - ./dev/database/mysql/seed-data:/seed-data
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sbp_mysql_database
      - MYSQL_USER=sbp
      - MYSQL_PASSWORD=sbp
  redis:
    image: redis:5.0.7
    container_name: sbp_redis_service
    ports:
      - "6379:6379"
    restart: always
  localstack:
    container_name: sbp_localstack
    image: localstack/localstack:3.0.2
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEFAULT_REGION=ap-southeast-1
      - AWS_DEFAULT_REGION=ap-southeast-1
      - USE_SSL=1
      - PERSISTENCE = 1
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - ./dev/ignore/localstack/var/lib/localstack:/var/lib/localstack
      - ./dev/ignore/localstack/var/run/docker.sock:/var/run/docker.sock
  mail-server:
    platform: linux/x86_64
    image: mailhog/mailhog:v1.0.1
    container_name: sbp-mail-server
    ports:
      - "1025:1025"
      - "8025:8025"
  cognitolocal:
    image: jagregory/cognito-local:3.23.2
    container_name: sbp_cognitolocal
    ports:
      - "9229:9229"
    volumes:
      - ./cognito:/usr/src/app/.cognito
