spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
  flyway:
    enabled: ${MIGRATE_DATABASE:false}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: db/migration
    default-schema: public
application:
  debug: false
  jwt:
    secret: ${APPLICATION_JWT_SECRET}
    expirationInSecond: ${APPLICATION_JWT_EXPIRATION_IN_SECOND}
  client:
    requestTimeOutInMillis: 5000
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
