spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  debug: false
  jwt:
    secret: ${APPLICATION_JWT_SECRET}
    expirationInSecond: ${APPLICATION_JWT_EXPIRATION_IN_SECOND}
