spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sbp_postgres_database
    username: sbp
    password: sbp
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  debug: true
  jwt:
    secret: c2RmS0o4NzgmXmpma3Nkaio3Zjc4RkpLRGoqN2ZkanNoKjc4N0tGS0Y
    expirationInSecond: 43200
