### SearchProductByKeyword
GET {{host}}/api/product?keyword=3
Authorization: Bearer {{member-jwt-token}}
Accept: application/json

### GetProduct
GET {{host}}/api/product/2
Authorization: Bearer {{member-jwt-token}}
Accept: application/json

### CreateProduct
POST {{host}}/api/product
Authorization: Bearer {{member-jwt-token}}
Content-Type: application/json
Accept: application/json

{
  "name": "New name",
  "note": "Hello"
}

### updateProduct
PUT {{host}}/api/product/5
Authorization: Bearer {{member-jwt-token}}
Content-Type: application/json
Accept: application/json

{
  "name": "New name update 2",
  "note": "Hello"
}

### deleteProduct
DELETE {{host}}/api/product/5
Authorization: Bearer {{admin-jwt-token}}
Accept: application/json
